// employee: 'THOMAS CARTER'
// endTime: ''
// objectiveActivityId: '204'
// objectiveActivityNote: 'jjhjjkbjjk'
// objectiveId: '363'
// objectiveRecurrance: 'W'
// objectiveSuccessDescription: 'Not Completed'
// objectiveSuccessSymbol: '-'
// objective_date: '10/4/2024 12:00:00 AM'
// promptNumber: '4'
// promptType: 'g'
// staffId: '7369'
// startTime: ''
